from dataclasses import dataclass


@dataclass
class JIRAIssue:
    key: str
    summary: str
    status: str
    issue_type: str


class DAOException(Exception):
    """Exceptions generated by DAOs"""
    def __init__(self, msg):
        super().__init__(msg)
        self.message = msg
