from dataclasses import dataclass


@dataclass
class JIRAIssue:
    key: str
    summary: str
    status: str
    issue_type: str


class DAOException(BaseException):
    """Exceptions generated by DAOs"""
